# Generated by Django 4.2.3 on 2023-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comments_listing_id_alter_comments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
